### ISSUE TITLE
Zips aren't great for version control

### ISSUE THREAD

**Issue by kornpow** [lnbits/lnbits-extensions#4]
Im going through and moving my `usermanager` PR from the main lnbits repo to here, and I see that all the extension code is zipped. Im sure you've thought through this but it makes development kind of difficult as you cannot do a `git diff` when working on updates to an extension.

I understand for distributing the extensions, the zipfile and json manifest is ideal.

# Dev Process: 
- Clone lnbits-extensions
- unzip extension you want to work on
- Make changes somewhat blind as there is no version control on the individual files you are updating
- Rezip, calculate hashes, and update manifest
- PR

Could this not be better to have *both* the zip file, and the uncompressed code in the repo?

# Better dev process?
- Clone lnbits-extensions
- make changes to extension you want to update
- Run "convenience script" which asks you what extension you want to package up. This script will zip, hash, and update manifests.
- PR

**Comment by fiatjaf** [comment]
See here: https://github.com/lnbits/usermanager-extension

**Comment by dni** [comment]
hey! there is now 1 extensions https://github.com/lnbits/lnbits-extensions/blob/main/extensions.json#L95

which uses the zip of github releases as download, maybe thats a little bit better :)

**Comment by prusnak** [comment]
Currently 15 out of 31 extensions are using autogenerated ZIPs by GitHub using the `https://github.com/{org}/{repo}/archive/refs/tags/{tag}.zip` link.

Recently, GitHub broke reproducibility of the ZIPs leading to changed hashes, but the change was reverted as GitHub realised this will break so much stuff on the internet. We can assume the ZIPs will stay reproducible for the foreseeable future. More details here: https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

I think this is a good way how to deal with the extensions and allows us to drop ZIPs from this repo.

**Comment by dni** [comment]
i agree with you we should move them out

**Comment by arbadacarbaYK** [comment]
could you pls make sure the readme will be available for linking ?

**Comment by dni** [comment]
yes the readme will sit in each extensions repo like here https://github.com/lnbits/boltz-extension/blob/main/README.md

**Comment by arcbtc** [comment]
I know its prob fine, I was just being superstitious. Lets pull out zips.

**Comment by dni** [comment]
working on it, first zip, pulled ;)

**Comment by prusnak** [comment]
So we nuked the in-repo ZIPs with https://github.com/lnbits/lnbits-extensions/pull/60 and GitHub autogenerated ZIPs are being used now.

I think this issue can be closed, or is there any improvement we can do on top of #60?

**Comment by dni** [comment]
@kornpow when you are satisfied for no please close, i think we can continue to improve from here in another issue.

**Comment by kornpow** [comment]
Hey thanks! Glad this was a helpful discussion.

Trying to get a PR merged in for an extension, let me know if I can improve this PR somewhere so I can get it landed.
https://github.com/lnbits/usermanager/pull/1
