### ISSUE TITLE
Extensions - Split-Payment - not saving target % value without new line

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits-extensions#52]
neither an invoice-key nor a wallet-id will be saved as target if not an additional empty row is generated (inactive save button otherwise)

<img width="765" alt="Bildschirm­foto 2023-02-20 um 17 32 13" src="https://user-images.githubusercontent.com/63317640/220160818-3613b527-dc18-4b22-8961-2d60d1f0908a.png">
<img width="793" alt="Bildschirm­foto 2023-02-20 um 17 31 27" src="https://user-images.githubusercontent.com/63317640/220160826-6d3e2360-f2b8-46e4-949b-bd248b19f643.png">

btw wouldnt a lnurlp work as well ?

**Comment by prusnak** [comment]
I think this issue belongs to https://github.com/lnbits/splitpayments ?

**Comment by arbadacarbaYK** [comment]
ok sorry, will close and reopen.
