### ISSUE TITLE
New manifest type to make developement easier

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits-extensions#8]
Following a discussion on telegram, is it possible to have a new manifest type, like `repos`, but release hashes are also included?
```
{
    "repos": [
        {
            "id": "gerty",
            "organisation": "lnbits",
            "repository": "gerty-extension"
            "releases": ["roiernoiwnre", "rvmpwoemiw", "etc"]
        }
    ]
}
```
LNbits goes and fetches the release zip and installs. Thi smeans developers wont have to do the manual hashing and uploading of zips, but they will still have to pr this repo for us to share their release via the vetted extensions.

**Comment by dni** [comment]
i like the idea and i would maybe go for something like this
```json
{
    "repos": [
        {
            "id": "gerty",
            "organisation": "lnbits",
            "repository": "gerty-extension"
            "releases": [
                {
                     "version": "0.1",
                     "commit-hash": "ebed1f7f6a3a68e3d19ff4770ae993858ea06c75"

                 }
             ]
        }
    ]
}
```

**Comment by motorina0** [comment]
Some context:
 - GitHub releases are NOT immutable, they can be changed after being vetted (replace the zip)
    - so some other method must be used to guarantee integrity
 - a `commit-hash` enforces integrity, but the GitHub `/releases` API does not give us the `commit-hash` only a tag name
    - I am not sure if it is possible to fetch a `commit-hash` from the tag
    - this is the only API that I've found: https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#about-git-tags
  - GitHub releases have the disadvantage that they zip the FULL repo (with documentation, tests, etc)
    - a manual `zip` can possibly be lighter

**Comment by arcbtc** [comment]
In that case I vote we keep the same. This repo is for vetted extensions. Just using `repos` means the extension is not vetted. Someone else can make a list of all extensions that is not vetted.

**Comment by dni** [comment]
@motorina0 
another possibility is adding the download link + shba256 hash of the file anyway

```json
{
    "repos": [
        {
            "id": "gerty",
            "organisation": "lnbits",
            "repository": "gerty-extension"
            "releases": [
                {
                     "version": "0.2.0",
                     "lnbits": "^1",
                     "sha256hash": "ebed1f7f6a3a68e3d19ff4770ae993858ea06c75",
                     "url": "https://github.com/dni/lnbits-smtp-extension/archive/refs/tags/0.2.0.zip"
                 }, {
                     "version": "0.1.3",
                     "lnbits": "^0",
                     "sha256hash": "ebed1f7f6a3a68e3d19ff4770ae993858ea06c75"
                      "url": "https://github.com/dni/lnbits-smtp-extension/archive/refs/tags/0.1.3.zip"
                 }
             ]
        }
    ]
}
```

**Comment by arcbtc** [comment]
The zip could still be changed later though right?

**Comment by dni** [comment]
thats why you will need to download this zip and sha256hash is also

                     ```"sha256hash": "ebed1f7f6a3a68e3d19ff4770ae993858ea06c75",```

**Comment by arcbtc** [comment]
The can do this in `extensions` already

**Comment by motorina0** [comment]
> @motorina0 another possibility is adding the download link + sha256 hash of the file anyway

 - this has disadvantages from both approaches:
   - it has to download and `shasum -a 256` the zip (not nice for non-technical people)
   - it archives the FULL repo (larger zip file)

**Comment by dni** [comment]
yes but then you will need to upload the zip to the repos, right?

**Comment by arcbtc** [comment]
No you can link to wherever

**Comment by dni** [comment]
> No you can link to wherever

wow, how did i miss that :)

**Comment by dni** [comment]
ok but still, having releases as array with lnbits version, is still smart, isnt it?

**Comment by motorina0** [comment]
> **Note**: the `extensions: []` mode has to be supported for people that do not want to use GitHub (maybe they have an internal LNbits instance blocked access to GitHub)

**Comment by motorina0** [comment]
> ok but still, having releases as array with lnbits version, is still smart, isnt it?

- `extension-to-server` compatibility is a must and should be implemented for both `repos: []` and `extensions[]`.
- lets handle that in a different thread though

**Comment by motorina0** [comment]
> GitHub releases have the disadvantage that they zip the FULL repo (with documentation, tests, etc)

- that is incorrect, files can be excluded from the automatically created `zip`
- see: https://gist.github.com/dleidert/30ff21de50e72ec4d042ee92777ff8f6
- example here: https://github.com/lnbits/nostr-relay-extension/blob/main/.gitattributes
